src/Web/Models/Courses/CourseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models.Courses
{
    public class CourseViewModel
    {
        public int Id { get; set; } = default!;
        public string Name { get; set; } = default!;
        public string Description { get; set; } = default!;
        public int ProblemsCount { get; set; } = default!;
    }
}

src/Web/Models/Courses/CreateCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Web.Models.Courses
{
    public class CreateCategoryViewModel
    {
        [Required]
        [HiddenInput]
        public int CourseId { get; set; } = default!;

        [Required]
        [HiddenInput]
        public string CourseName { get; set; } = default!;

        [HiddenInput]
        public int? CategoryParentId { get; set; } = default!;

        [Required]
        [Display(Name = "Category Name")]
        public string Name { get; set; } = default!;
    }
}

src/Web/Controllers/CourseController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Framework;
using Web.Models.Courses;
using Framework.Services;
using Microsoft.AspNetCore.Authorization;
using Data.Models;

namespace Web.Controllers;

public class CourseController : AcadnetController
{
    private readonly ICourseService _courseService;

    public CourseController(
        ICourseService courseService
    )
    {
        _courseService = courseService;
    }

    public IActionResult Index([FromQuery] string? filterMaintainer = default!)
    {
        var _courses = _courseService.GetCourses(filterMaintainer);

        var _output = new List<CourseViewModel>();

        foreach (var _course in _courses)
        {
            _output.Add(new CourseViewModel
            {
                Id = _course.Id,
                Name = _course.Name,
                Description = _course.Description,
                ProblemsCount = _courseService.GetProblemsCount(_course)
            });
        }

        return View(_output);
    }

    [HttpGet]
    [Authorize(Roles = "ProblemAuthor")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [Authorize(Roles = "ProblemAuthor")]
    [ValidateAntiForgeryToken]
    public IActionResult Create(CreateCourseViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var _course = Mapper.Map<Course>(model);

        _courseService.CreateCourse(_course);

        AddSuccess("Course created successfully!");

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public IActionResult Categories([FromQuery] int courseId, [FromQuery] int? categoryParent = default!)
    {
        var _course = _courseService.GetCourse(courseId);

        if (_course == null)
        {
            return NotFound();
        }

        var _categories = _courseService.GetCategories(_course, categoryParent);
        var model = new CategoriesViewModel
        {
            CourseId = _course.Id,
            CourseName = _course.Name,
            Categories = Mapper.Map<List<CategoryViewModel>>(_categories),
            CategoryParent = categoryParent,
        };

        // the category has a name only if it is not the root category
        var categoryName = string.Empty;
        if (categoryParent != null)
        {
            var _categoryParent = _courseService.GetCategory(categoryParent.Value);

            if (_categoryParent == null)
            {
                return NotFound();
            }

            model.CategoryName = _categoryParent.Name;
            model.Problems = Mapper.Map<List<ProblemInCategoryViewModel>>(_categoryParent.Problems);

            foreach (var _problem in model.Problems)
            {
                _problem.IsSolved = SecurityContext.IsAuthenticated ? _courseService.IsProblemSolved(_problem.Id, SecurityContext.User!) : false;
            }
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult CreateCategory([FromQuery] int courseId, [FromQuery] int? categoryParent = default!)
    {
        var _course = _courseService.GetCourse(courseId);

        if (_course == null)
        {
            return NotFound();
        }

        var _categories = _courseService.GetCategories(_course, categoryParent);

        return View(new CreateCategoryViewModel
        {
            CourseId = _course.Id,
            CourseName = _course.Name,
            CategoryParentId = categoryParent
        });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "ProblemAuthor")]
    public IActionResult CreateCategory(CreateCategoryViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var _course = _courseService.GetCourse(model.CourseId);

        if (_course == null)
        {
            return NotFound();
        }

        var _category = new Category { Name = model.Name };

        _courseService.CreateCategory(_course, _category, model.CategoryParentId);

        AddSuccess("Category created successfully!");

        return RedirectToAction(nameof(Categories), new { courseId = model.CourseId, categoryParent = model.CategoryParentId });
    }
}

src/Web/Controllers/ProblemController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Framework;
using Web.Models.Problem;
using Framework.Services;
using Data.Models;
using Data.Models.Enums;
using Data.S3;
using CommunityToolkit.HighPerformance.Helpers;
using System.Text;
using System.Web;
using Framework.Services.ProblemServices;
using Framework.Services.FileServices;
using Microsoft.AspNetCore.Authorization;

namespace Web.Controllers;

[Authorize]
public class ProblemController : AcadnetController
{
    private readonly ProblemServiceFactory _problemServiceFactory;
    private readonly ICourseService _categoryService;
    private readonly IFileService _fileService;
    private readonly ICheckerService _checkerService;
    private readonly IWorkspaceService _workspaceService;

    public ProblemController(
        ProblemServiceFactory problemServiceFactory,
        ICourseService categoryService,
        FileServiceFactory fileServiceFactory,
        ICheckerService checkerService,
        IWorkspaceService workspaceService
    )
    {
        _problemServiceFactory = problemServiceFactory;
        _categoryService = categoryService;
        _fileService = fileServiceFactory.GetFileService();
        _checkerService = checkerService;
        _workspaceService = workspaceService;
    }

    [HttpGet]
    public IActionResult Create([FromQuery] int? categoryId)
    {
        if (categoryId == null)
        {
            AddError("Category not found!");
            return RedirectToAction("Index", "Course");
        }

        return View(new CreateProblemViewModel { CategoryId = categoryId });
    }

    [HttpPost]
    public IActionResult Create(CreateProblemViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var _category = _categoryService.GetCategory(model.CategoryId!.Value);

        if (_category == null)
        {
            AddError("Category not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problem = new Problem
        {
            Name = model.Name,
            // problems are incomplete after creation, because they don't have any files
            Status = ProblemStatus.Incomplete,
            Category = _category,
            Type = model.ProblemType
        };

        var _problemService = _problemServiceFactory.GetServiceByType(_problem.Type);
        _problemService.CreateProblem(_problem);

        // get course to know where to return
        var _course = _categoryService.GetCourseByCategory(_category.Id);

        return RedirectToAction("Categories", "Course", new { courseId = _course!.Id, categoryParent = _category.Id });
    }

    [HttpGet]
    public IActionResult Solve([FromQuery] int? problemId = default!)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null || _problem.Status != ProblemStatus.Ready)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _output = new SolveProblemViewModel
        {
            Id = _problem.Id,
            Name = _problem.Name,
            StatementHtml = _problemService.GetProblemStatementHtml(_problem),
            IsSolved = _problemService.HasSolvedProblem(_problem, SecurityContext.User!)
        };

        return View(_output);
    }

    [HttpGet]
    public IActionResult Edit([FromQuery] int? problemId = default!)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _output = Mapper.Map<EditProblemViewModel>(_problem);

        // get files in bucket
        var _files = _fileService.GetFilesInBucket(_problem.FilesBucketName);
        _output.Files = _files.Select(x => x.BucketName + "/" + x.FileName).ToList();

        return View(_output);
    }

    [HttpPost]
    // upload endpoint for uploading file multipart/form-data
    public async Task<IActionResult> Upload([FromQuery] string bucketName)
    {
        var file = Request.Form.Files[0];
        // read file and save it to file service
        var _s3object = new S3Object
        {
            BucketName = bucketName,
            FileName = file.FileName,
            ContentType = file.ContentType
        };

        _s3object.Content = file.OpenReadStream();

        try
        {
            await _fileService.UploadFileAsync(_s3object);
        }
        catch (Exception e)
        {
            return BadRequest($"<span class=\"fw-600\">{file.FileName}</span> {e.Message}");
        }

        return Ok(bucketName + "/" + file.FileName);
    }

    [HttpDelete]
    public async Task<IActionResult> Remove()
    {
        // read raw body
        var bodyReader = await Request.BodyReader.ReadAsync();
        var fileLocation = EncodingExtensions.GetString(Encoding.UTF8, bodyReader.Buffer);

        var bucket = fileLocation.Split("/")[0];
        var fileName = fileLocation.Split("/")[1];

        await _fileService.DeleteFileAsync(bucket, fileName);

        return Ok();
    }

    // route is /problem/load/{bucket}/{fileName}
    [HttpGet]
    [Route("problem/load/{fileLocation}")]
    public async Task<IActionResult> Load(string fileLocation)
    {
        fileLocation = HttpUtility.UrlDecode(fileLocation);
        var bucket = fileLocation.Split("/")[0];
        var fileName = fileLocation.Split("/")[1];

        var _s3object = await _fileService.DownloadFileAsync(bucket, fileName);

        if (_s3object == null)
        {
            return NotFound();
        }

        Response.Headers.Add("Content-Disposition", $"inline; filename=\"{fileName}\"");

        return File(_s3object.Content, _s3object.ContentType);
    }

    [HttpGet]
    public IActionResult Check([FromQuery] int? problemId)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        // get files in bucket
        var _files = _fileService.GetFilesInBucket(_problem.FilesBucketName);

        var _output = new CheckStructureViewModel();

        // README.md
        _output.ReadmePresent = _files.Any(x => x.FileName == "README.md");
        _output.ReadmeError = !_output.ReadmePresent ? "file is missing" : null;

        // bad source
        _output.BadSourcePresent = _files.Any(x => x.FileName == "main.cpp");
        _output.BadSourceError = !_output.BadSourcePresent ? "file is missing" : null;

        // good source
        _output.GoodSourcePresent = _files.Any(x => x.FileName == "solution_main.cpp");
        _output.GoodSourceError = !_output.GoodSourcePresent ? "file is missing" : null;

        // test cases
        _output.InputTestsCount = _files.Count(x => x.FileName.StartsWith("test") && x.FileName.EndsWith(".in"));
        _output.InputTestsError = _output.InputTestsCount == 0 ? "no input tests found" : null;
        _output.RefTestsCount = _files.Count(x => x.FileName.StartsWith("test") && x.FileName.EndsWith(".ref"));
        _output.RefTestsError = _output.RefTestsCount == 0 ? "no output tests found" : null;

        _output.SolutionOk = _problem.SolutionSubmission?.Status == SubmissionStatus.Passed;

        // if solution is ok, update problem status
        if (_output.SolutionOk)
        {
            _problemService.MakeProblemReady(_problem);
        }

        return PartialView("_CheckStructurePartial", _output);
    }

    [HttpGet]
    public IActionResult DownloadSource([FromQuery] int? problemId)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null || _problem.Status != ProblemStatus.Ready)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        // get source
        var _source = _problemService.GetProblemSource(_problem);

        var _memorySource = new MemoryStream();
        _source.Content.CopyTo(_memorySource);


        return File(_memorySource.ToArray(), "text/plain", $"{_problem.Name}.cpp");
    }

    [HttpGet]
    public async Task<IActionResult> CheckSolution([FromQuery] int? problemId)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        // download solution
        var _solution = _problemService.GetProblemSolution(_problem);

        if (_solution == null)
        {
            AddError("Solution not found!");

src/Web/Views/Course/Categories.cshtml
@model CategoriesViewModel

@using Framework.Services
@inject ICourseService CourseService

@using Data.Models.Enums

@{
  ViewData["Title"] = "Explore problems";
}

<section data-anim="fade" class="breadcrumbs ">
  <div class="container">
    <div class="row">
      <div class="col-auto">
        <div class="breadcrumbs__content">

          <div class="breadcrumbs__item ">
            <a href="#">Home</a>
          </div>

          <div class="breadcrumbs__item ">
            <a href="#">Courses</a>
          </div>

          @* TODO: add breadcrumbs *@

        </div>
      </div>
    </div>
  </div>
</section>


<section class="page-header -type-1">
  <div class="container">
    <div class="page-header__content">
      <div class="row">
        <div class="col-auto">
          <div data-anim="slide-up delay-1">
            <h1 class="mb-10">@Model.CourseName</h1>
            <h3 class="text-purple-4">@Model.CategoryName</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="layout-pt-md layout-pb-lg">
  <div data-anim-wrap class="container">
    <div data-anim="slide-up delay-1" class="accordion js-accordion">
      <div class="row mb-10">
        <div class="col-auto">
          <a href="javascript:history.back()" class="button -sm -purple-1 text-white -icon">
            <i class="fas fa-backward text-13 mr-10"></i>Go back</a>
        </div>
      </div>
      <div class="row y-gap-20 items-center justify-between pb-30">
        <div class="col-auto">
          <div class="text-14 lh-12">Showing <span class="text-dark-1 fw-500">@Model.Categories.Count</span> total
            results</div>
        </div>
      </div>
    </div>

    <div class="row y-gap-30">
      @foreach (var category in Model.Categories)
      {
        <div data-anim-child="slide-up delay-1" class="col-lg-4 col-md-6">
          <a asp-action="Categories" asp-route-courseId="@Model.CourseId" asp-route-categoryParent="@category.Id"
            class="coursesCard -type-1 rounded-8 bg-purple-5 shadow-4">
            <div class="h-100 pt-20 pb-15 px-30 row justify-content-between">
              <div class="col-auto text-20 lh-15 fw-500 text-dark-1 mt-10">@category.Name</div>
              <div class="col-auto">
                <button class="button -md -outline-purple-1 text-purple-1 -icon">Explore
                  <i class="icon-arrow-top-right text-13 ml-10"></i>
                </button>
              </div>

            </div>
          </a>
        </div>
      }

      @foreach (var problem in Model.Problems.Where(x => x.Status == ProblemStatus.Ready).ToList())
      {
        @if (problem.IsSolved)
        {
          <div data-anim-child="slide-up delay-1" class="col-lg-4 col-md-6">
            <a asp-action="Solve" asp-controller="Problem" asp-route-problemId="@problem.Id"
              class="coursesCard -type-1 rounded-8 bg-green-7 shadow-4">
              <div class="h-100 pt-20 pb-15 px-30 row justify-content-between">
                <div class="col-auto lh-15 mt-10">
                  <div class="text-20 fw-500 text-dark-1 mb-4">@problem.Name</div>
                  <span class="text-dark-1"><i class="fas fa-check-circle text-20 mr-3"></i>Solved</span>
                </div>
                <div class="col-auto">
                  <button class="button -md -outline-dark-3 text-dark-3 -icon">View
                    <i class="icon-arrow-top-right text-13 ml-10"></i>
                  </button>
                </div>

              </div>
            </a>
          </div>
        }
        else
        {
          <div data-anim-child="slide-up delay-1" class="col-lg-4 col-md-6">
            <a asp-action="Solve" asp-controller="Problem" asp-route-problemId="@problem.Id"
              class="coursesCard -type-1 rounded-8 bg-yellow-5 shadow-4">
              <div class="h-100 pt-20 pb-15 px-30 row justify-content-between">
                <div class="col-auto text-20 lh-15 fw-500 text-dark-1 mt-10">@problem.Name</div>
                <div class="col-auto">
                  <button class="button -md -outline-yellow-1 text-yellow-1 -icon">Solve
                    <i class="icon-arrow-top-right text-13 ml-10"></i>
                  </button>
                </div>

              </div>
            </a>
          </div>
        }
      }

      @* maintainer *@
      @if (SecurityContext.IsAuthenticated && CourseService.IsMaintainer(Model.CourseId, SecurityContext.User!))
      {
        // show hidden problems
        @foreach (var problem in Model.Problems.Where(x => x.Status == ProblemStatus.Incomplete).ToList())
        {
          <div data-anim-child="slide-up delay-1" class="col-lg-4 col-md-6">
            <div class="coursesCard -type-1 rounded-8 bg-yellow-2 shadow-4">
              <div class="h-100 pt-20 pb-15 px-30 row justify-content-between">
                <div class="col-auto text-20 lh-15 fw-500 text-dark-1 mt-10">@problem.Name</div>
                <div class="col-auto mt-10">
                  <a asp-action="Edit" asp-controller="Problem" asp-route-problemId="@problem.Id"
                    class="button -sm -green-5 text-white -icon w-1/3">Edit</a>
                </div>
              </div>
              <div class="row px-30 pb-15 justify-content-start">
                <span class="text-red-3"><i class="fas fa-file-circle-exclamation text-20 mr-10"></i>Incomplete</span>
              </div>
            </div>
          </div>
        }

        @foreach (var problem in Model.Problems.Where(x => x.Status == ProblemStatus.Hidden).ToList())
        {
          <div data-anim-child="slide-up delay-1" class="col-lg-4 col-md-6">
            <div class="coursesCard -type-1 rounded-8 bg-yellow-2 shadow-4">
              <div class="h-100 pt-20 pb-15 px-30 row justify-content-between">
                <div class="col-auto text-20 lh-15 fw-500 text-dark-1 mt-10">@problem.Name</div>
                <div class="col-auto mt-10">
                  <a asp-action="Edit" asp-controller="Problem" asp-route-problemId="@problem.Id"
                    class="button -sm -green-5 text-white -icon w-1/3">Edit</a>
                </div>
              </div>
              <div class="row px-30 pb-15 justify-content-start">
                <span><i class="fas fa-eye-slash text-20 mr-10"></i>Hidden</span>
              </div>
            </div>
          </div>
        }

        <div data-anim-child="slide-up delay-1" class="col-lg-4 col-md-6">
          <div class="coursesCard -type-1 rounded-8 bg-white-1 shadow-4">
            <div class="row">
              <div class="col-auto">
                <div class="px-30 text-12 text-dark-1 mt-10">Because you are a maintainer, you can
                </div>
              </div>
            </div>
            <div class="h-100 pt-20 pb-15 px-30 row justify-content-between">
              <div class="col-auto">
                <a asp-action="CreateCategory" asp-route-courseId="@Model.CourseId"
                  asp-route-categoryParent="@Model.CategoryParent" class="button -sm -purple-1 text-white -icon">Add
                  category</a>
              </div>
              @if (Model.CategoryParent != null)
              {
                <div class="col-auto">
                  <a asp-action="Create" asp-controller="Problem" asp-route-categoryId="@Model.CategoryParent"
                    class="button -sm -yellow-1 text-white -icon">Add problem</a>
                </div>
              }
              else
              {
                <p>You need to have at least one subcategory to create a problem</p>
              }
            </div>
          </div>
        </div>
      }
    </div>
  </div>
</section>

src/Web/Views/Course/Create.cshtml
@model CreateCourseViewModel

@{
    ViewData["Title"] = "Create course";
}

<section class="page-header -type-1 mt-90">
  <div class="container">
    <div class="page-header__content">
      <div class="row">
        <div class="col-auto">
          <div data-anim="slide-up delay-1">
            <h1 class="page-header__title">Create course</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="layout-pt-md layout-pb-md">
  <div data-anim="slide-up delay-2" class="container">
    <div class="row y-gap-20 items-center justify-between pb-30">
      <div class="col-auto">
        <form class="contact-form y-gap-30" asp-action="Create" method="post">
          <div class="form-group">
            <label asp-for="Name" class="text-16 lh-1 fw-500 text-dark-1 mb-10"></label>
            <input asp-for="Name" placeholder="Name">
            <span asp-validation-for="Name" class="text-red-1"></span>
          </div>
          <div class="form-group">
            <label asp-for="Description" class="text-16 lh-1 fw-500 text-dark-1 mb-10"></label>
            <textarea asp-for="Description" placeholder="Description"></textarea>
            <span asp-validation-for="Description" class="text-red-1"></span>
          </div>
          @Html.AntiForgeryToken()
          <button class="button -md -dark-1 text-white -icon" type="submit">Create course
            <i class="fas fa-check ml-10"></i>
          </button>
        </form>
      </div>
    </div>
  </div>
</section>

src/Web/Views/Course/CreateCategory.cshtml
@model CreateCategoryViewModel

@{
  ViewData["Title"] = "Create category";
}

<section class="page-header -type-1 mt-90">
  <div class="container">
    <div class="page-header__content">
      <div class="row">
        <div class="col-auto">
          <div data-anim="slide-up delay-1">
            <h1 class="page-header__title">Create category for</h1>
            <h4 class="page-header__text">@Model.CourseName</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="layout-pt-md layout-pb-md">
  <div data-anim="slide-up delay-2" class="container">
    <div class="row y-gap-20 items-center justify-between pb-30">
      <div class="col-auto">
        <form class="contact-form y-gap-30" asp-action="CreateCategory" method="post">
          <div class="form-group">
            <label asp-for="Name" class="text-16 lh-1 fw-500 text-dark-1 mb-10"></label>
            <input asp-for="Name" placeholder="Name">
            <span asp-validation-for="Name" class="text-red-1"></span>
          </div>
          @Html.AntiForgeryToken()
          <input asp-for="CourseId" hidden />
          <input asp-for="CourseName" hidden />
          <input asp-for="CategoryParentId" hidden />

          <button class="button -md -dark-1 text-white -icon" type="submit">Create category
            <i class="fas fa-check ml-10"></i>
          </button>
        </form>
      </div>
    </div>
  </div>
</section>

src/Web/Views/Course/Index.cshtml
@model ICollection<CourseViewModel>

@{
  ViewData["Title"] = "Explore problems";
}

<section data-anim="fade" class="breadcrumbs ">
  <div class="container">
    <div class="row">
      <div class="col-auto">
        <div class="breadcrumbs__content">

          <div class="breadcrumbs__item ">
            <a href="#">Home</a>
          </div>

          <div class="breadcrumbs__item ">
            <a href="#">Courses</a>
          </div>

          @* TODO: add breadcrumbs *@

        </div>
      </div>
    </div>
  </div>
</section>


<section class="page-header -type-1">
  <div class="container">
    <div class="page-header__content">
      <div class="row">
        <div class="col-auto">
          <div data-anim="slide-up delay-1">
            <h1 class="page-header__title">Select a course and start practicing</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="layout-pt-md layout-pb-md">
  <div data-anim="slide-up delay-2" class="container">
    <div class="row y-gap-20 items-center justify-between pb-30">
      <div class="col-auto">
        @if (SecurityContext.UserHasRole(UserRole.ProblemAuthor))
        {
          <a class="button -md -yellow-1 text-white -icon" asp-action="Create" asp-controller="Course">Add course
            <i class="fas fa-plus ml-10"></i>
          </a>
        }
        <div class="text-14 lh-12 mt-30">Showing <span class="text-dark-1 fw-500">@Model.Count</span> total
          results</div>
      </div>
    </div>

    <div class="row y-gap-60">

      @foreach (var course in Model)
      {
        <div class="col-12 border-bottom-light">
          <a asp-action="Categories" asp-route-courseId="@course.Id"
            class="coursesCard -type-1 row y-gap-20 flex-row items-center">
            <div class="col-xl-3 col-lg-4">
              <div class="coursesCard__image rounded-8 relative">
                <img class="w-1/1 rounded-8" src="https://acadnet.ro/images/banners/acadnet_nou.png" alt="image">
                <div class="coursesCard__image_overlay rounded-8"></div>
              </div>
            </div>

            <div class="col">
              <div class="col-12 text-20 lh-15 fw-500 text-dark-1 mt-10">@course.Name
              </div>
              <div class="mt-8">@course.Description</div>

              <div class="row x-gap-10 y-gap-10 items-center pt-10">
                <div class="col-auto">
                  <div class="d-flex items-center">
                    <img class="mr-8" src="~/img/coursesCards/icons/1.svg" alt="icon">
                    @* TODO: add number of problems *@
                    <div class="text-14 lh-1">@course.ProblemsCount problems</div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-auto md:d-none">
              <div class="line -vertical -h-120 bg-light-5 ml-60 lg:ml-20 md:ml-0"></div>
            </div>

            <div class="col-md-auto">
              <div class="row x-gap-20 y-gap-20 items-center pt-25">
                <div class="col-auto">
                  <button class="button -md -outline-purple-1 text-purple-1 -icon">Explore
                    <i class="icon-arrow-top-right text-13 ml-10"></i>
                  </button>
                </div>
              </div>
            </div>
          </a>
        </div>
      }

    </div>
  </div>
</section>