src/Web/Models/Problem/CreateProblemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Data.Models.Enums;

namespace Web.Models.Problem
{
    public class CreateProblemViewModel
    {
        [Required]
        [Display(Name = "Problem Name")]
        public string Name { get; set; } = default!;

        [Required]
        [HiddenInput]
        public int? CategoryId { get; set; } = default!;

        [Required]
        [Display(Name = "Problem Type")]
        public ProblemType ProblemType { get; set; } = default!;
    }
}

src/Web/Models/Problem/EditProblemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Web.Models.Problem
{
    public class EditProblemViewModel
    {
        public int Id { get; set; } = default!;

        public string Name { get; set; } = default!;

        public string FilesBucketName { get; set; } = default!;
        public ICollection<string> Files { get; set; } = default!;
    }

    public class CheckStructureViewModel
    {
        public bool ReadmePresent { get; set; } = default!;
        public string? ReadmeError { get; set; }

        public bool BadSourcePresent { get; set; } = default!;
        public string? BadSourceError { get; set; }

        public bool GoodSourcePresent { get; set; } = default!;
        public string? GoodSourceError { get; set; }

        public int InputTestsCount { get; set; } = default!;
        public string? InputTestsError { get; set; }

        public int RefTestsCount { get; set; } = default!;
        public string? RefTestsError { get; set; }

        public bool SolutionOk { get; set; } = default!;
    }
}

src/Web/Models/Problem/SolveProblemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models.Problem
{
    public class SolveProblemViewModel
    {
        public int Id { get; set; } = default!;
        public string Name { get; set; } = default!;
        public string StatementHtml { get; set; } = default!;
        public bool IsSolved { get; set; } = default!;
    }
}

src/Web/Models/Problem/SubmissionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models.Problem
{
    public class SubmissionViewModel
    {
        public string ProblemName { get; set; } = default!;
    }
}

src/Web/Controllers/ProblemController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Framework;
using Web.Models.Problem;
using Framework.Services;
using Data.Models;
using Data.Models.Enums;
using Data.S3;
using CommunityToolkit.HighPerformance.Helpers;
using System.Text;
using System.Web;
using Framework.Services.ProblemServices;
using Framework.Services.FileServices;
using Microsoft.AspNetCore.Authorization;

namespace Web.Controllers;

[Authorize]
public class ProblemController : AcadnetController
{
    private readonly ProblemServiceFactory _problemServiceFactory;
    private readonly ICourseService _categoryService;
    private readonly IFileService _fileService;
    private readonly ICheckerService _checkerService;
    private readonly IWorkspaceService _workspaceService;

    public ProblemController(
        ProblemServiceFactory problemServiceFactory,
        ICourseService categoryService,
        FileServiceFactory fileServiceFactory,
        ICheckerService checkerService,
        IWorkspaceService workspaceService
    )
    {
        _problemServiceFactory = problemServiceFactory;
        _categoryService = categoryService;
        _fileService = fileServiceFactory.GetFileService();
        _checkerService = checkerService;
        _workspaceService = workspaceService;
    }

    [HttpGet]
    public IActionResult Create([FromQuery] int? categoryId)
    {
        if (categoryId == null)
        {
            AddError("Category not found!");
            return RedirectToAction("Index", "Course");
        }

        return View(new CreateProblemViewModel { CategoryId = categoryId });
    }

    [HttpPost]
    public IActionResult Create(CreateProblemViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var _category = _categoryService.GetCategory(model.CategoryId!.Value);

        if (_category == null)
        {
            AddError("Category not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problem = new Problem
        {
            Name = model.Name,
            // problems are incomplete after creation, because they don't have any files
            Status = ProblemStatus.Incomplete,
            Category = _category,
            Type = model.ProblemType
        };

        var _problemService = _problemServiceFactory.GetServiceByType(_problem.Type);
        _problemService.CreateProblem(_problem);

        // get course to know where to return
        var _course = _categoryService.GetCourseByCategory(_category.Id);

        return RedirectToAction("Categories", "Course", new { courseId = _course!.Id, categoryParent = _category.Id });
    }

    [HttpGet]
    public IActionResult Solve([FromQuery] int? problemId = default!)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null || _problem.Status != ProblemStatus.Ready)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _output = new SolveProblemViewModel
        {
            Id = _problem.Id,
            Name = _problem.Name,
            StatementHtml = _problemService.GetProblemStatementHtml(_problem),
            IsSolved = _problemService.HasSolvedProblem(_problem, SecurityContext.User!)
        };

        return View(_output);
    }

    [HttpGet]
    public IActionResult Edit([FromQuery] int? problemId = default!)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _output = Mapper.Map<EditProblemViewModel>(_problem);

        // get files in bucket
        var _files = _fileService.GetFilesInBucket(_problem.FilesBucketName);
        _output.Files = _files.Select(x => x.BucketName + "/" + x.FileName).ToList();

        return View(_output);
    }

    [HttpPost]
    // upload endpoint for uploading file multipart/form-data
    public async Task<IActionResult> Upload([FromQuery] string bucketName)
    {
        var file = Request.Form.Files[0];
        // read file and save it to file service
        var _s3object = new S3Object
        {
            BucketName = bucketName,
            FileName = file.FileName,
            ContentType = file.ContentType
        };

        _s3object.Content = file.OpenReadStream();

        try
        {
            await _fileService.UploadFileAsync(_s3object);
        }
        catch (Exception e)
        {
            return BadRequest($"<span class=\"fw-600\">{file.FileName}</span> {e.Message}");
        }

        return Ok(bucketName + "/" + file.FileName);
    }

    [HttpDelete]
    public async Task<IActionResult> Remove()
    {
        // read raw body
        var bodyReader = await Request.BodyReader.ReadAsync();
        var fileLocation = EncodingExtensions.GetString(Encoding.UTF8, bodyReader.Buffer);

        var bucket = fileLocation.Split("/")[0];
        var fileName = fileLocation.Split("/")[1];

        await _fileService.DeleteFileAsync(bucket, fileName);

        return Ok();
    }

    // route is /problem/load/{bucket}/{fileName}
    [HttpGet]
    [Route("problem/load/{fileLocation}")]
    public async Task<IActionResult> Load(string fileLocation)
    {
        fileLocation = HttpUtility.UrlDecode(fileLocation);
        var bucket = fileLocation.Split("/")[0];
        var fileName = fileLocation.Split("/")[1];

        var _s3object = await _fileService.DownloadFileAsync(bucket, fileName);

        if (_s3object == null)
        {
            return NotFound();
        }

        Response.Headers.Add("Content-Disposition", $"inline; filename=\"{fileName}\"");

        return File(_s3object.Content, _s3object.ContentType);
    }

    [HttpGet]
    public IActionResult Check([FromQuery] int? problemId)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        // get files in bucket
        var _files = _fileService.GetFilesInBucket(_problem.FilesBucketName);

        var _output = new CheckStructureViewModel();

        // README.md
        _output.ReadmePresent = _files.Any(x => x.FileName == "README.md");
        _output.ReadmeError = !_output.ReadmePresent ? "file is missing" : null;

        // bad source
        _output.BadSourcePresent = _files.Any(x => x.FileName == "main.cpp");
        _output.BadSourceError = !_output.BadSourcePresent ? "file is missing" : null;

        // good source
        _output.GoodSourcePresent = _files.Any(x => x.FileName == "solution_main.cpp");
        _output.GoodSourceError = !_output.GoodSourcePresent ? "file is missing" : null;

        // test cases
        _output.InputTestsCount = _files.Count(x => x.FileName.StartsWith("test") && x.FileName.EndsWith(".in"));
        _output.InputTestsError = _output.InputTestsCount == 0 ? "no input tests found" : null;
        _output.RefTestsCount = _files.Count(x => x.FileName.StartsWith("test") && x.FileName.EndsWith(".ref"));
        _output.RefTestsError = _output.RefTestsCount == 0 ? "no output tests found" : null;

        _output.SolutionOk = _problem.SolutionSubmission?.Status == SubmissionStatus.Passed;

        // if solution is ok, update problem status
        if (_output.SolutionOk)
        {
            _problemService.MakeProblemReady(_problem);
        }

        return PartialView("_CheckStructurePartial", _output);
    }

    [HttpGet]
    public IActionResult DownloadSource([FromQuery] int? problemId)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null || _problem.Status != ProblemStatus.Ready)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        // get source
        var _source = _problemService.GetProblemSource(_problem);

        var _memorySource = new MemoryStream();
        _source.Content.CopyTo(_memorySource);


        return File(_memorySource.ToArray(), "text/plain", $"{_problem.Name}.cpp");
    }

    [HttpGet]
    public async Task<IActionResult> CheckSolution([FromQuery] int? problemId)
    {
        if (problemId == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        var _problemService = _problemServiceFactory.GetServiceById(problemId.Value);
        var _problem = _problemService.GetProblem(problemId.Value);

        if (_problem == null)
        {
            AddError("Problem not found!");
            return RedirectToAction("Index", "Course");
        }

        // download solution
        var _solution = _problemService.GetProblemSolution(_problem);

        if (_solution == null)
        {
            AddError("Solution not found!");

src/Web/Controllers/WorkspaceController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Framework;
using System.Web.Mvc;
using Framework.Services;
using Data;
using Data.Models;
using System.Web;

namespace Web.Controllers;

[Authorize]
public class WorkspaceController : AcadnetController
{
    private readonly IWorkspaceService _workspaceService;
    private readonly Database _database;

    public WorkspaceController(
        IWorkspaceService workspaceService,
        Database database
    )
    {
        _workspaceService = workspaceService;
        _database = database;
    }

    public IActionResult LaunchWorkspace([FromQuery] int? problemId)
    {
        if (problemId == null)
        {
            return BadRequest();
        }

        var problem = _database.Problems.Find(problemId);

        if (problem == null)
        {
            return NotFound();
        }

        var workspaceId = _workspaceService.GetWorkspaceId(problem, SecurityContext.User!);

        // set cookie
        Response.Cookies.Append(Consts.WORKSPACE_ID_COOKIE_NAME, workspaceId);

        return Redirect("/code?folder=" + _workspaceService.GetWorkspaceProblemPath(workspaceId));
    }
}

src/Web/Views/Problem/Create.cshtml
@model CreateProblemViewModel

@{
  ViewData["Title"] = "Create problem";
}

<section class="page-header -type-1 mt-90">
  <div class="container">
    <div class="page-header__content">
      <div class="row">
        <div class="col-auto">
          <div data-anim="slide-up delay-1">
            <h1 class="page-header__title">Create problem</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="layout-pt-md layout-pb-md">
  <div data-anim="slide-up delay-2" class="container">
    <div class="row y-gap-20 items-center justify-between pb-30">
      <div class="col-auto">
        <form class="contact-form y-gap-30" asp-action="Create" method="post">
          <div class="form-group">
            <label asp-for="Name" class="text-16 lh-1 fw-500 text-dark-1 mb-10"></label>
            <input asp-for="Name" placeholder="Name">
            <span asp-validation-for="Name" class="text-red-1"></span>
          </div>
          <input asp-for="CategoryId" type="hidden" />
          <span asp-validation-for="CategoryId" class="text-red-1"></span>
          @Html.AntiForgeryToken()
          <button class="button -md -dark-1 text-white -icon" type="submit">Create problem
            <i class="fas fa-check ml-10"></i>
          </button>
        </form>
      </div>
    </div>
  </div>
</section>

src/Web/Views/Problem/Edit.cshtml
@model EditProblemViewModel

@{
  ViewData["Title"] = "Edit problem - " + Model.Name;
}

<section class="page-header -type-1 mt-90">
  <div class="container">
    <div class="page-header__content">
      <div class="row">
        <div class="col-auto">
          <div data-anim="slide-up delay-1">
            <h1 class="page-header__title">Edit problem - @Model.Name</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="layout-pt-md layout-pb-md">
  <div data-anim="slide-up delay-2" class="container">
    <div class="row y-gap-20 items-center justify-between pb-30">
      <div id="check_container">
      </div>
    </div>
    <div class="row y-gap-20 items-center justify-between pb-30">
      <div id="submission_result_container" style="display: none;">
        <h4>Submission details</h4>
        <p>Id: <span id="submission_id" class="fw-600"></span></p>
        <p>Status: <span id="submission_status" class="fw-600">Not polled yet</span></p>
      </div>
    </div>
    <div class="row y-gap-20 items-center justify-between pb-30">
      <div class="col-md-4">
        <input type="file" id="problem_files_pond" class="filepond" name="filepond" multiple data-allow-reorder="true"
          data-max-file-size="5MB" data-max-files="30">
      </div>
    </div>
  </div>
</section>

@section Styles {
  <!-- Filepond stylesheet -->
  <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
  <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
}

@section Scripts {
  <!-- FilePond -->
  <script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>
  <script src="https://unpkg.com/filepond/dist/filepond.min.js"></script>
  <script src="https://unpkg.com/jquery-filepond/filepond.jquery.js"></script>

  <script>
    $.fn.filepond.registerPlugin(FilePondPluginFileValidateSize);

    const inputElement = document.querySelector('input[id="problem_files_pond"]');

    const checkProblemStructure = () => {
      $.ajax({
        url: '/problem/check?problemId=@Model.Id',
        type: 'GET',
        success: (response) => {
          $('#check_container').html(response);
        },
        error: (xhr, status, error) => {
          notie.alert({type: 'error', text: error, position: 'bottom'});
        }
      });
    };

    FilePond.create(inputElement, {
      server: {
        process: {
          url: '/problem/upload?bucketName=@Model.FilesBucketName',
          onerror: (response) => {
            notie.alert({type: 'error', text: response, position: 'bottom'});
            return response;
          }
        },
        revert: '/problem/remove',
        load: '/problem/load/',
        remove: (source, load, error) => {
          $.ajax({
            url: '/problem/remove',
            type: 'DELETE',
            data: source,
            contentType: 'text/plain',
            success: () => {
              load();
            },
            error: (xhr, status, error) => {
              error(error);
            }
          });
        }
      },
      files: [@foreach (var file in Model.Files)
    {
      <text>{source: '@file', options: {type: 'local' }},</text>
    }]
    });

    // event listeners to update the check container
    document.addEventListener('FilePond:loaded', (e) => {
      checkProblemStructure();
    });

    document.addEventListener('FilePond:processfile', (e) => {
      checkProblemStructure();
    });

    document.addEventListener('FilePond:updatefiles', (e) => {
      checkProblemStructure();
    });

    let checkInterval = null;

    // solution checker
    $("#check_container").on('click', '.check-solution', function () {
      var problemId = "@Model.Id";

      // hide the check button
      $(this).hide();

      $.ajax({
        url: '/problem/CheckSolution?problemId=' + problemId,
        type: 'GET',
        success: (response) => {
          $('#submission_result_container').show();
          $('#submission_id').text(response.submissionId);

          checkInterval = setInterval(() => {
            $.ajax({
              url: '/problem/CheckSubmission?submissionId=' + response.submissionId,
              type: 'GET',
              success: (response) => {
                $('#submission_status').text(response.status);

                if (response.status !== 'Pending') {
                  clearInterval(checkInterval);

                  // show errors if any
                  if (response.status === 'Failed') {
                    response.errors.forEach(error => {
                      $('#submission_result_container').append('<div><h6>' + error.type + '</h6><p style="white-space: pre-line">' + error.message + '</p></div>');
                    });
                  }

                  if (response.status === 'Passed') {
                    checkProblemStructure();
                  }
                }
              },
              error: (xhr, status, error) => {
                notie.alert({type: 'error', text: error, position: 'bottom'});
              }
            });
          }, 1000);
        },
        error: (xhr, status, error) => {
          notie.alert({type: 'error', text: error, position: 'bottom'});
        }
      });
    });
  </script>
}

src/Web/Views/Problem/Solve.cshtml
@model SolveProblemViewModel

@{
  ViewData["Title"] = "Solve - " + Model.Name;
}

<section class="page-header -type-1 mt-90">
  <div class="container">
    <div class="page-header__content">
      <div class="row">
        <div class="col-auto">
          <div data-anim="slide-up delay-1">
            <h1 class="page-header__title">Solve - @Model.Name</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="">
  <div data-anim="slide-up delay-2" class="container">
    <div class="row items-start justify-between pb-30">
      <div class="col-md-9 col-12 markdown-container">
        @Html.Raw(Model.StatementHtml)
      </div>
      <div class="col-auto text-center" id="solve_options_container">
        <div class="markdown-container">
          <h6>Solve the problem on your computer</h6>
          <div class="mt-10">
            <a asp-action="DownloadSource" asp-route-problemId="@Model.Id" target="_blank"
              class="button -md -outline-purple-1 text-purple-1 -icon">Download sources
              <i class="fas fa-file-arrow-down ml-10 text-20"></i>
            </a>
          </div>
          <div id="submission_upload_container">
            <p class="my-2">and</p>
            <input type="file" id="submission_pond" class="filepond" name="filepond" multiple data-allow-reorder="true"
              data-max-file-size="5MB" data-max-files="1">
          </div>
        </div>
        <h6 class="mt-30">or</h6>
        <div class="markdown-container mt-30">
          <h6>Solve the problem online</h6>
          <div class="mt-10">
            <a asp-action="LaunchWorkspace" asp-controller="Workspace" asp-route-problemId="@Model.Id"
              class="button -md -orange-1 text-white -icon">Solve online
              <i class="fas fa-cloud-arrow-up ml-10 text-20"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-auto text-center" id="solved_container" style="display: none;">
        <div class="markdown-container">
          <h6 class="text-green-5">You have already solved this problem</h6>
          <div class="mt-10">
            <button class="button -md -purple-1 text-white -icon" id="solve_again">Solve again
              <i class="fas fa-repeat ml-10 text-20"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="row pb-30">
      <div class="col-auto">
        <div id="submission_result_container" style="display: none;">
          <button class="button -sm -red-3 text-white mb-10" id="try_again" style="display: none;">Try again
            <i class="fas fa-repeat ml-10 text-20"></i>
          </button>
          <h4>Submission details</h4>
          <p>Id: <span id="submission_id" class="fw-600"></span></p>
          <p>Status: <span id="submission_status" class="fw-600">Not polled yet</span></p>
        </div>
      </div>
    </div>
  </div>
</section>

@section Styles {
  <!-- Filepond stylesheet -->
  <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
  <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
}

@section Scripts {
  <!-- FilePond -->
  <script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>
  <script src="https://unpkg.com/filepond/dist/filepond.min.js"></script>
  <script src="https://unpkg.com/jquery-filepond/filepond.jquery.js"></script>

  <script>
    $.fn.filepond.registerPlugin(FilePondPluginFileValidateSize);

    const inputElement = document.querySelector('input[id="submission_pond"]');

    let checkInterval = null;

    function problemSolved() {
      $('#solve_options_container').hide();
      $('#solved_container').show();
    }

    @if (Model.IsSolved)
    {
      <text>
          problemSolved();
      </text>
    }

      $('#solve_again').click(() => {
        $('#solve_options_container').show();
        $('#solved_container').hide();
        $('#submission_upload_container').show();
      });

    $('#try_again').click(() => {
      $('#submission_result_container').hide();
      $('#submission_upload_container').show();

      pond.removeFiles();
      $(".test-error").remove();

      $('#try_again').hide();
    });

    const pond = FilePond.create(inputElement, {
      labelIdle: 'Upload your submission - <span class="filepond--label-action"> Browse </span>',
      server: {
        process: {
          url: '/problem/UploadSubmission?problemId=@Model.Id',
          onerror: (response) => {
            notie.alert({type: 'error', text: response, position: 'bottom'});
            return response;
          },
          onload: (response) => {
            response = JSON.parse(response);

            $('#submission_result_container').show();
            $('#submission_id').text(response.submissionId);
            $('#submission_upload_container').hide();

            checkInterval = setInterval(() => {
              $.ajax({
                url: '/problem/CheckSubmission?submissionId=' + response.submissionId,
                type: 'GET',
                success: (response) => {
                  $('#submission_status').text(response.status);

                  if (response.status !== 'Pending') {
                    clearInterval(checkInterval);

                    // show errors if any
                    if (response.status === 'Failed') {
                      $('#submission_status').attr('class', 'text-red-1 fw-600');
                      response.errors.forEach(error => {
                        $('#submission_result_container').append('<div class="test-error mt-10"><h6>' + error.type + '</h6><p style="white-space: pre-line">' + error.message + '</p></div>');
                      });
                      $('#try_again').show();
                    }

                    if (response.status === 'Passed') {
                      $('#submission_status').attr('class', 'text-green-5 fw-600');
                      problemSolved();
                    }
                  } else {
                    $('#submission_status').attr('class', 'text-purple-4 fw-600');
                    $('#submission_status').text('Checking... Do NOT refresh the page!');
                  }
                },
                error: (xhr, status, error) => {
                  notie.alert({type: 'error', text: error, position: 'bottom'});
                }
              });
            }, 1000);

            return response;
          }
        },
      }
    });
  </script>
}

src/Web/Views/Problem/Submission.cshtml
@model SubmissionViewModel

@{
  ViewData["Title"] = "Submission - " + Model.ProblemName;
}

<section class="page-header -type-1 mt-90">
  <div class="container">
    <div class="page-header__content">
      <div class="row">
        <div class="col-auto">
          <div data-anim="slide-up delay-1">
            <h1 class="page-header__title">Submission - @Model.ProblemName</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="layout-pt-md layout-pb-md">
  <div data-anim="slide-up delay-2" class="container">
    <div class="row y-gap-20 items-center justify-between pb-30">
      <div class="col-md-4">
        <input type="file" id="problem_files_pond" class="filepond" name="filepond" multiple data-allow-reorder="true"
          data-max-file-size="5MB" data-max-files="30">
      </div>
    </div>
  </div>
</section>

src/Web/Views/Problem/_CheckStructurePartial.cshtml
@model CheckStructureViewModel

@{
  var complete = Model.ReadmePresent && Model.BadSourcePresent && Model.GoodSourcePresent && Model.InputTestsCount > 0 &&
  Model.RefTestsCount > 0 && Model.InputTestsCount == Model.RefTestsCount;
}

<div class="row justify-content-between">
  <div class="col-md-4">
    <h4 class="">Problem structure checks</h4>
    <div class="d-flex flex-column">
      @if (Model.ReadmePresent)
      {
        <span class="text-green-5"><i class="fas fa-circle-check mr-5"></i>README.md</span>
      }
      else
      {
        <span class="text-red-3"><i class="fas fa-circle-exclamation mr-5"></i>README.md - @Model.ReadmeError</span>
      }

      @if (Model.BadSourcePresent)
      {
        <span class="text-green-5"><i class="fas fa-circle-check mr-5"></i>main.cpp</span>
      }
      else
      {
        <span class="text-red-3"><i class="fas fa-circle-exclamation mr-5"></i>main.cpp - @Model.BadSourceError</span>
      }

      @if (Model.GoodSourcePresent)
      {
        <span class="text-green-5"><i class="fas fa-circle-check mr-5"></i>solution_main.cpp</span>
      }
      else
      {
        <span class="text-red-3"><i class="fas fa-circle-exclamation mr-5"></i>solution_main.cpp -
          @Model.GoodSourceError</span>
      }

      @if (Model.InputTestsCount > 0)
      {
        <span class="text-green-5"><i class="fas fa-circle-check mr-5"></i>@Model.InputTestsCount input tests</span>
      }
      else
      {
        <span class="text-red-3"><i class="fas fa-circle-exclamation mr-5"></i>input tests - @Model.InputTestsError</span>
      }

      @if (Model.RefTestsCount > 0)
      {
        <span class="text-green-5"><i class="fas fa-circle-check mr-5"></i>@Model.RefTestsCount reference tests</span>
      }
      else
      {
        <span class="text-red-3"><i class="fas fa-circle-exclamation mr-5"></i>reference tests -
          @Model.RefTestsError</span>
      }

      @if (Model.InputTestsCount > 0 && Model.RefTestsCount > 0 && Model.InputTestsCount != Model.RefTestsCount)
      {
        <span class="text-red-3"><i class="fas fa-circle-exclamation mr-5"></i>input / ref count mismatch
          (@Model.InputTestsCount vs @Model.RefTestsCount)</span>
      }
    </div>
  </div>
  <div class="col-md-4">
    <h4>Problem roadmap</h4>
    <div class="d-flex flex-column y-gap-5 pt-10">
      <p class="text-20 text-green-5">Incomplete</p>
      <span class='@(complete ? "text-green-5" : "")'><i class='fas fa-down-long text-20 mr-5'></i>TODO: add necessary
        files</span>
      <p class='text-20 @(complete ? "text-green-5" : "")'>All files uploaded</p>
      <span class='@(Model.SolutionOk ? "text-green-5" : "")'><i class='fas fa-down-long text-20 mr-5'></i>TODO: check
        if good solution passes tests</span>
      <p class='text-20 @(Model.SolutionOk ? "text-green-5" : "")'>Ready to solve</p>
      @if (complete && !Model.SolutionOk)
      {
        <button class="button -md -yellow-1 text-white -icon mt-20 check-solution">Check good solution passes tests
          (Submit)
          <i class="fas fa-check ml-10"></i>
        </button>
      }
    </div>
  </div>
</div>